### ISSUE TITLE
Release 1.1.0 is missing "*.swu" asset

### ISSUE THREAD

**Issue by gokhanbarisaker** [turing-machines/BMC-Firmware#105]
**Describe the bug**
As a user, I would like to download a pre-built swu file to be able to upgrade

**To Reproduce**
1. Go to https://github.com/turing-machines/BMC-Firmware/releases/tag/1.1.0
2. Scroll down to 'Assets'
3. Observe that the swu file is not among the uploaded assets

**Expected behavior**
A downloadable swu file to be available under each release

**Screenshots**
<img width="1237" alt="Screenshot 2023-07-29 at 13 17 49" src="https://github.com/turing-machines/BMC-Firmware/assets/914990/2f8c18a9-c605-475c-9221-2050a088fad1">

**Versions**
-

**Additional context**
-

**Comment by svenrademakers** [comment]
The missing .swu file is intentional. Providing kernel updates inside the .swu package could brick your device if you don't have a Windows machine to rewrite the flash on your board. The decision is therefore made to be conservative and not distribute a .swu asset for this release. We expect to have an alternative solution in place in the near future. tracking #35 #36.

**Comment by gokhanbarisaker** [comment]
Makes sense. Would it be possible the highlight this situation on either the release page or the documentation? As someone with not enough knowledge, it feels like the upgrade is not possible until those issues are resolved

**Comment by svenrademakers** [comment]
This is something we should do asap. Thanks for the input! we will be updating the docs in the course of next week 👍

**Comment by suranyami** [comment]
Is there reference information anywhere as to what the Windows-specific software/hardware is that is needed to re-flash if BMC is bricked?

I'd be keen to have a go at porting it to linux/macOS if it's just software.

**Comment by svenrademakers** [comment]
The Windows tool in question is called [PhoenixSuit](https://docs.turingpi.com/docs/turing-pi2-bmc-update#flashing-on-a-windows-host). There are multiple hoops you need to jump through if you were to attempt such thing.
* The generated .img is fully proprietary. You would need to spend a lot of time reverse-engineering the format or do a new thing, which implies a major overhaul of the build script and tools. 
* Secondly, the flash driver on the board is also proprietary, you would need to work around the SIMULATE_MULTIPLANE mode which is enabled. 

I would strongly discourage you not do it. Not only because of the effort involved, but also because we are well underway of doing some major refactoring here to move away from all this proprietary stuff.

**Comment by svenrademakers** [comment]
Updated the release notes with a small explanation of the missing .swu asset. Further developments with regards to firmware update will be tracked with #36.
